version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - BACKEND_URL=http://backend:5001
    command: flask run --host=0.0.0.0 --port=5000 --reload
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - MONGODB_URI=mongodb://mongodb:27017/formdb
    command: flask run --host=0.0.0.0 --port=5001 --reload
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: